remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme 
gem "github-pages", group: :jekyll_plugins
title: Hank The Tank Web Interface
description: The web interface for the holy Hank The Tank. The best 3D printer ever
